config/routes.rb
Rails.application.routes.draw do
  resources :student_professor_subjects
  resources :professor_subjects
  post '/rate' => 'rater#create', :as => 'rate'
  resources :professors
  resources :subjects
  resources :home
  root to: "home#index"
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_professor_subject.rb
class StudentProfessorSubject < ApplicationRecord
  belongs_to :student
  belongs_to :professor_subject

  validates_uniqueness_of :student_id, scope: :professor_subject_id
end

app/controllers/student_professor_subjects_controller.rb
class StudentProfessorSubjectsController < ApplicationController
  before_action :set_student_professor_subject, only: [:update]

  # PATCH/PUT /student_professor_subjects/1
  # PATCH/PUT /student_professor_subjects/1.json
  def update
    respond_to do |format|
      if @student_professor_subject.update(student_professor_subject_params)
        format.html { redirect_to @student_professor_subject }
        format.json { render :show, status: :ok, location: @student_professor_subject }
      else
        format.html { render :edit }
        format.json { render json: @student_professor_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_professor_subject
      @student_professor_subject = StudentProfessorSubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_professor_subject_params
      params.require(:student_professor_subject).permit(:student_id, :professor_subject_id, :description)
    end
end

app/views/student_professor_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_professor_subject.student_id %>
</p>

<p>
  <strong>Professor subject:</strong>
  <%= @student_professor_subject.professor_subject_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @student_professor_subject.description %>
</p>

<%= link_to 'Edit', edit_student_professor_subject_path(@student_professor_subject) %> |
<%= link_to 'Back', student_professor_subjects_path %>