config/routes.rb
Rails.application.routes.draw do
  resources :student_professor_subjects
  resources :professor_subjects
  post '/rate' => 'rater#create', :as => 'rate'
  resources :professors
  resources :subjects
  resources :home
  root to: "home#index"
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor_subject.rb
class ProfessorSubject < ApplicationRecord
  ratyrate_rateable "overall_rate"
  belongs_to :professor
  belongs_to :subject
  has_many :student_professor_subjects

  validates_uniqueness_of :professor_id, scope: :subject_id
end

app/controllers/professor_subjects_controller.rb
class ProfessorSubjectsController < ApplicationController
  before_action :set_professor_subject, only: [:show, :edit, :update, :destroy]

  # GET /professor_subjects
  # GET /professor_subjects.json
  def index
    @professor_subjects = ProfessorSubject.all
    @subjects = Subject.all
    @professors = Professor.all
  end

  # GET /professor_subjects/1
  # GET /professor_subjects/1.json
  def show
  end

  # GET /professor_subjects/new
  def new
    @professor_subject = ProfessorSubject.new
  end

  # GET /professor_subjects/1/edit
  def edit
  end

  # POST /professor_subjects
  # POST /professor_subjects.json
  def create
    @professor_subject = ProfessorSubject.new(professor_subject_params)

    respond_to do |format|
      if @professor_subject.save
        format.html { redirect_to @professor_subject, notice: 'Professor subject was successfully created.' }
        format.json { render :show, status: :created, location: @professor_subject }
      else
        format.html { render :new }
        format.json { render json: @professor_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professor_subjects/1
  # PATCH/PUT /professor_subjects/1.json
  def update
    respond_to do |format|
      if @professor_subject.update(professor_subject_params)
        format.html { redirect_to @professor_subject, notice: 'Professor subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor_subject }
      else
        format.html { render :edit }
        format.json { render json: @professor_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professor_subjects/1
  # DELETE /professor_subjects/1.json
  def destroy
    @professor_subject.destroy
    respond_to do |format|
      format.html { redirect_to professor_subjects_url, notice: 'Professor subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor_subject
      @professor_subject = ProfessorSubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_subject_params
      params.require(:professor_subject).permit(:subject_id, :professor_id)
    end
end

app/helpers/professor_subjects_helper.rb
module ProfessorSubjectsHelper
end

app/views/professor_subjects/index.html.erb
<div id="professor_subjects"></div>

<script type="text/javascript">
  $(function() {
    window.router = new Edukasyon.Routers.ProfessorSubjectsRouter(
      {
        professorSubjects: <%= @professor_subjects.to_json.html_safe -%>,
        subjects: <%= @subjects.to_json.html_safe -%>,
        professors: <%= @professors.to_json.html_safe -%>
      });
    Backbone.history.stop();
    Backbone.history.start();
  });
</script>

app/views/professor_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @professor_subject.subject_id %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @professor_subject.professor_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @professor_subject.description %>
</p>

<%= link_to 'Edit', edit_professor_subject_path(@professor_subject) %> |
<%= link_to 'Back', professor_subjects_path %>